// Generated by gencpp from file crosbot_map/GetSnap.msg
// DO NOT EDIT!


#ifndef CROSBOT_MAP_MESSAGE_GETSNAP_H
#define CROSBOT_MAP_MESSAGE_GETSNAP_H

#include <ros/service_traits.h>


#include <crosbot_map/GetSnapRequest.h>
#include <crosbot_map/GetSnapResponse.h>


namespace crosbot_map
{

struct GetSnap
{

typedef GetSnapRequest Request;
typedef GetSnapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSnap
} // namespace crosbot_map


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crosbot_map::GetSnap > {
  static const char* value()
  {
    return "ed02702e11dc9a36e98cb929d7f780ba";
  }

  static const char* value(const ::crosbot_map::GetSnap&) { return value(); }
};

template<>
struct DataType< ::crosbot_map::GetSnap > {
  static const char* value()
  {
    return "crosbot_map/GetSnap";
  }

  static const char* value(const ::crosbot_map::GetSnap&) { return value(); }
};


// service_traits::MD5Sum< ::crosbot_map::GetSnapRequest> should match 
// service_traits::MD5Sum< ::crosbot_map::GetSnap > 
template<>
struct MD5Sum< ::crosbot_map::GetSnapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_map::GetSnap >::value();
  }
  static const char* value(const ::crosbot_map::GetSnapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_map::GetSnapRequest> should match 
// service_traits::DataType< ::crosbot_map::GetSnap > 
template<>
struct DataType< ::crosbot_map::GetSnapRequest>
{
  static const char* value()
  {
    return DataType< ::crosbot_map::GetSnap >::value();
  }
  static const char* value(const ::crosbot_map::GetSnapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crosbot_map::GetSnapResponse> should match 
// service_traits::MD5Sum< ::crosbot_map::GetSnap > 
template<>
struct MD5Sum< ::crosbot_map::GetSnapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_map::GetSnap >::value();
  }
  static const char* value(const ::crosbot_map::GetSnapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_map::GetSnapResponse> should match 
// service_traits::DataType< ::crosbot_map::GetSnap > 
template<>
struct DataType< ::crosbot_map::GetSnapResponse>
{
  static const char* value()
  {
    return DataType< ::crosbot_map::GetSnap >::value();
  }
  static const char* value(const ::crosbot_map::GetSnapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CROSBOT_MAP_MESSAGE_GETSNAP_H
