// Generated by gencpp from file crosbot_map/GetSnapRequest.msg
// DO NOT EDIT!


#ifndef CROSBOT_MAP_MESSAGE_GETSNAPREQUEST_H
#define CROSBOT_MAP_MESSAGE_GETSNAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32.h>
#include <std_msgs/UInt8.h>

namespace crosbot_map
{
template <class ContainerAllocator>
struct GetSnapRequest_
{
  typedef GetSnapRequest_<ContainerAllocator> Type;

  GetSnapRequest_()
    : id()
    , type()  {
    }
  GetSnapRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , type(_alloc)  {
    }



   typedef  ::std_msgs::Int32_<ContainerAllocator>  _id_type;
  _id_type id;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _type_type;
  _type_type type;




  typedef boost::shared_ptr< ::crosbot_map::GetSnapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crosbot_map::GetSnapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSnapRequest_

typedef ::crosbot_map::GetSnapRequest_<std::allocator<void> > GetSnapRequest;

typedef boost::shared_ptr< ::crosbot_map::GetSnapRequest > GetSnapRequestPtr;
typedef boost::shared_ptr< ::crosbot_map::GetSnapRequest const> GetSnapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crosbot_map::GetSnapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crosbot_map::GetSnapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crosbot_map

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'crosbot_map': ['/home/otan/3431/ass1/src/crosbot/crosbot_map/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'crosbot': ['/home/otan/3431/ass1/src/crosbot/crosbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_map::GetSnapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_map::GetSnapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_map::GetSnapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_map::GetSnapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_map::GetSnapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_map::GetSnapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crosbot_map::GetSnapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5b8a24a7431a27d7ce0f6285d812cfe";
  }

  static const char* value(const ::crosbot_map::GetSnapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5b8a24a7431a27dULL;
  static const uint64_t static_value2 = 0x7ce0f6285d812cfeULL;
};

template<class ContainerAllocator>
struct DataType< ::crosbot_map::GetSnapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crosbot_map/GetSnapRequest";
  }

  static const char* value(const ::crosbot_map::GetSnapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crosbot_map::GetSnapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int32 id\n\
std_msgs/UInt8 type\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
================================================================================\n\
MSG: std_msgs/UInt8\n\
uint8 data\n\
";
  }

  static const char* value(const ::crosbot_map::GetSnapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crosbot_map::GetSnapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetSnapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crosbot_map::GetSnapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crosbot_map::GetSnapRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CROSBOT_MAP_MESSAGE_GETSNAPREQUEST_H
