// Generated by gencpp from file crosbot_map/ListSnapsRequest.msg
// DO NOT EDIT!


#ifndef CROSBOT_MAP_MESSAGE_LISTSNAPSREQUEST_H
#define CROSBOT_MAP_MESSAGE_LISTSNAPSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crosbot_map
{
template <class ContainerAllocator>
struct ListSnapsRequest_
{
  typedef ListSnapsRequest_<ContainerAllocator> Type;

  ListSnapsRequest_()
    {
    }
  ListSnapsRequest_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ListSnapsRequest_

typedef ::crosbot_map::ListSnapsRequest_<std::allocator<void> > ListSnapsRequest;

typedef boost::shared_ptr< ::crosbot_map::ListSnapsRequest > ListSnapsRequestPtr;
typedef boost::shared_ptr< ::crosbot_map::ListSnapsRequest const> ListSnapsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crosbot_map::ListSnapsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crosbot_map

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'crosbot_map': ['/home/otan/3431/ass1/src/crosbot/crosbot_map/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'crosbot': ['/home/otan/3431/ass1/src/crosbot/crosbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::crosbot_map::ListSnapsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crosbot_map/ListSnapsRequest";
  }

  static const char* value(const ::crosbot_map::ListSnapsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::crosbot_map::ListSnapsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ListSnapsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crosbot_map::ListSnapsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::crosbot_map::ListSnapsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CROSBOT_MAP_MESSAGE_LISTSNAPSREQUEST_H
