// Generated by gencpp from file crosbot_map/ModifySnapRequest.msg
// DO NOT EDIT!


#ifndef CROSBOT_MAP_MESSAGE_MODIFYSNAPREQUEST_H
#define CROSBOT_MAP_MESSAGE_MODIFYSNAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/String.h>

namespace crosbot_map
{
template <class ContainerAllocator>
struct ModifySnapRequest_
{
  typedef ModifySnapRequest_<ContainerAllocator> Type;

  ModifySnapRequest_()
    : id()
    , type()
    , status()
    , description()  {
    }
  ModifySnapRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , type(_alloc)
    , status(_alloc)
    , description(_alloc)  {
    }



   typedef  ::std_msgs::Int32_<ContainerAllocator>  _id_type;
  _id_type id;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _type_type;
  _type_type type;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _status_type;
  _status_type status;

   typedef  ::std_msgs::String_<ContainerAllocator>  _description_type;
  _description_type description;




  typedef boost::shared_ptr< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ModifySnapRequest_

typedef ::crosbot_map::ModifySnapRequest_<std::allocator<void> > ModifySnapRequest;

typedef boost::shared_ptr< ::crosbot_map::ModifySnapRequest > ModifySnapRequestPtr;
typedef boost::shared_ptr< ::crosbot_map::ModifySnapRequest const> ModifySnapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crosbot_map::ModifySnapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crosbot_map

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'crosbot_map': ['/home/otan/3431/ass1/src/crosbot/crosbot_map/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'crosbot': ['/home/otan/3431/ass1/src/crosbot/crosbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1c64c0c3bf7d1de1b6bf7e6bbdda46c";
  }

  static const char* value(const ::crosbot_map::ModifySnapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1c64c0c3bf7d1deULL;
  static const uint64_t static_value2 = 0x1b6bf7e6bbdda46cULL;
};

template<class ContainerAllocator>
struct DataType< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crosbot_map/ModifySnapRequest";
  }

  static const char* value(const ::crosbot_map::ModifySnapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int32  id\n\
std_msgs/UInt8  type\n\
std_msgs/UInt8  status\n\
std_msgs/String description\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
================================================================================\n\
MSG: std_msgs/UInt8\n\
uint8 data\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::crosbot_map::ModifySnapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.status);
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ModifySnapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crosbot_map::ModifySnapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crosbot_map::ModifySnapRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
    s << indent << "description: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CROSBOT_MAP_MESSAGE_MODIFYSNAPREQUEST_H
