// Generated by gencpp from file crosbot_map/ModifySnap.msg
// DO NOT EDIT!


#ifndef CROSBOT_MAP_MESSAGE_MODIFYSNAP_H
#define CROSBOT_MAP_MESSAGE_MODIFYSNAP_H

#include <ros/service_traits.h>


#include <crosbot_map/ModifySnapRequest.h>
#include <crosbot_map/ModifySnapResponse.h>


namespace crosbot_map
{

struct ModifySnap
{

typedef ModifySnapRequest Request;
typedef ModifySnapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModifySnap
} // namespace crosbot_map


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crosbot_map::ModifySnap > {
  static const char* value()
  {
    return "c1c64c0c3bf7d1de1b6bf7e6bbdda46c";
  }

  static const char* value(const ::crosbot_map::ModifySnap&) { return value(); }
};

template<>
struct DataType< ::crosbot_map::ModifySnap > {
  static const char* value()
  {
    return "crosbot_map/ModifySnap";
  }

  static const char* value(const ::crosbot_map::ModifySnap&) { return value(); }
};


// service_traits::MD5Sum< ::crosbot_map::ModifySnapRequest> should match 
// service_traits::MD5Sum< ::crosbot_map::ModifySnap > 
template<>
struct MD5Sum< ::crosbot_map::ModifySnapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_map::ModifySnap >::value();
  }
  static const char* value(const ::crosbot_map::ModifySnapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_map::ModifySnapRequest> should match 
// service_traits::DataType< ::crosbot_map::ModifySnap > 
template<>
struct DataType< ::crosbot_map::ModifySnapRequest>
{
  static const char* value()
  {
    return DataType< ::crosbot_map::ModifySnap >::value();
  }
  static const char* value(const ::crosbot_map::ModifySnapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crosbot_map::ModifySnapResponse> should match 
// service_traits::MD5Sum< ::crosbot_map::ModifySnap > 
template<>
struct MD5Sum< ::crosbot_map::ModifySnapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_map::ModifySnap >::value();
  }
  static const char* value(const ::crosbot_map::ModifySnapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_map::ModifySnapResponse> should match 
// service_traits::DataType< ::crosbot_map::ModifySnap > 
template<>
struct DataType< ::crosbot_map::ModifySnapResponse>
{
  static const char* value()
  {
    return DataType< ::crosbot_map::ModifySnap >::value();
  }
  static const char* value(const ::crosbot_map::ModifySnapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CROSBOT_MAP_MESSAGE_MODIFYSNAP_H
