// Generated by gencpp from file crosbot_map/SnapMsg.msg
// DO NOT EDIT!


#ifndef CROSBOT_MAP_MESSAGE_SNAPMSG_H
#define CROSBOT_MAP_MESSAGE_SNAPMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <sensor_msgs/Image.h>
#include <crosbot/PointCloudMsg.h>

namespace crosbot_map
{
template <class ContainerAllocator>
struct SnapMsg_
{
  typedef SnapMsg_<ContainerAllocator> Type;

  SnapMsg_()
    : header()
    , type(0)
    , status(0)
    , id(0)
    , description()
    , robot()
    , pose()
    , images()
    , clouds()  {
    }
  SnapMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(0)
    , status(0)
    , id(0)
    , description(_alloc)
    , robot(_alloc)
    , pose(_alloc)
    , images(_alloc)
    , clouds(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _type_type;
  _type_type type;

   typedef int8_t _status_type;
  _status_type status;

   typedef uint32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _robot_type;
  _robot_type robot;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::Image_<ContainerAllocator> >::other >  _images_type;
  _images_type images;

   typedef std::vector< ::crosbot::PointCloudMsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::crosbot::PointCloudMsg_<ContainerAllocator> >::other >  _clouds_type;
  _clouds_type clouds;




  typedef boost::shared_ptr< ::crosbot_map::SnapMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crosbot_map::SnapMsg_<ContainerAllocator> const> ConstPtr;

}; // struct SnapMsg_

typedef ::crosbot_map::SnapMsg_<std::allocator<void> > SnapMsg;

typedef boost::shared_ptr< ::crosbot_map::SnapMsg > SnapMsgPtr;
typedef boost::shared_ptr< ::crosbot_map::SnapMsg const> SnapMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crosbot_map::SnapMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crosbot_map::SnapMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crosbot_map

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'crosbot_map': ['/home/otan/3431/ass1/src/crosbot/crosbot_map/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'crosbot': ['/home/otan/3431/ass1/src/crosbot/crosbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_map::SnapMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_map::SnapMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_map::SnapMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_map::SnapMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_map::SnapMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_map::SnapMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crosbot_map::SnapMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e22c37cf6db46fd5970eb0de2b60055b";
  }

  static const char* value(const ::crosbot_map::SnapMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe22c37cf6db46fd5ULL;
  static const uint64_t static_value2 = 0x970eb0de2b60055bULL;
};

template<class ContainerAllocator>
struct DataType< ::crosbot_map::SnapMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crosbot_map/SnapMsg";
  }

  static const char* value(const ::crosbot_map::SnapMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crosbot_map::SnapMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 type\n\
int8 status\n\
uint32 id\n\
string description\n\
geometry_msgs/Pose robot    # Global to given frame\n\
geometry_msgs/Pose pose     # Robot relative\n\
\n\
sensor_msgs/Image[] images\n\
crosbot/PointCloudMsg[] clouds\n\
#crosbot/ColouredCloudMsg[] colouredClouds\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: crosbot/PointCloudMsg\n\
Header header\n\
geometry_msgs/Point[] points	# The points in the cloud.\n\
ColourMsg[] colours				# The colours of the points. Can be empty.\n\
================================================================================\n\
MSG: crosbot/ColourMsg\n\
uint8 r\n\
uint8 g\n\
uint8 b\n\
uint8 a\n\
";
  }

  static const char* value(const ::crosbot_map::SnapMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crosbot_map::SnapMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.status);
      stream.next(m.id);
      stream.next(m.description);
      stream.next(m.robot);
      stream.next(m.pose);
      stream.next(m.images);
      stream.next(m.clouds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SnapMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crosbot_map::SnapMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crosbot_map::SnapMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
    s << indent << "robot: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.robot);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "images[]" << std::endl;
    for (size_t i = 0; i < v.images.size(); ++i)
    {
      s << indent << "  images[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "    ", v.images[i]);
    }
    s << indent << "clouds[]" << std::endl;
    for (size_t i = 0; i < v.clouds.size(); ++i)
    {
      s << indent << "  clouds[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::crosbot::PointCloudMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.clouds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CROSBOT_MAP_MESSAGE_SNAPMSG_H
