// Generated by gencpp from file crosbot_ogmbicp/GetRecentScans.msg
// DO NOT EDIT!


#ifndef CROSBOT_OGMBICP_MESSAGE_GETRECENTSCANS_H
#define CROSBOT_OGMBICP_MESSAGE_GETRECENTSCANS_H

#include <ros/service_traits.h>


#include <crosbot_ogmbicp/GetRecentScansRequest.h>
#include <crosbot_ogmbicp/GetRecentScansResponse.h>


namespace crosbot_ogmbicp
{

struct GetRecentScans
{

typedef GetRecentScansRequest Request;
typedef GetRecentScansResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRecentScans
} // namespace crosbot_ogmbicp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crosbot_ogmbicp::GetRecentScans > {
  static const char* value()
  {
    return "f920aef0166f130f16d65011603c0109";
  }

  static const char* value(const ::crosbot_ogmbicp::GetRecentScans&) { return value(); }
};

template<>
struct DataType< ::crosbot_ogmbicp::GetRecentScans > {
  static const char* value()
  {
    return "crosbot_ogmbicp/GetRecentScans";
  }

  static const char* value(const ::crosbot_ogmbicp::GetRecentScans&) { return value(); }
};


// service_traits::MD5Sum< ::crosbot_ogmbicp::GetRecentScansRequest> should match 
// service_traits::MD5Sum< ::crosbot_ogmbicp::GetRecentScans > 
template<>
struct MD5Sum< ::crosbot_ogmbicp::GetRecentScansRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_ogmbicp::GetRecentScans >::value();
  }
  static const char* value(const ::crosbot_ogmbicp::GetRecentScansRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_ogmbicp::GetRecentScansRequest> should match 
// service_traits::DataType< ::crosbot_ogmbicp::GetRecentScans > 
template<>
struct DataType< ::crosbot_ogmbicp::GetRecentScansRequest>
{
  static const char* value()
  {
    return DataType< ::crosbot_ogmbicp::GetRecentScans >::value();
  }
  static const char* value(const ::crosbot_ogmbicp::GetRecentScansRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crosbot_ogmbicp::GetRecentScansResponse> should match 
// service_traits::MD5Sum< ::crosbot_ogmbicp::GetRecentScans > 
template<>
struct MD5Sum< ::crosbot_ogmbicp::GetRecentScansResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_ogmbicp::GetRecentScans >::value();
  }
  static const char* value(const ::crosbot_ogmbicp::GetRecentScansResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_ogmbicp::GetRecentScansResponse> should match 
// service_traits::DataType< ::crosbot_ogmbicp::GetRecentScans > 
template<>
struct DataType< ::crosbot_ogmbicp::GetRecentScansResponse>
{
  static const char* value()
  {
    return DataType< ::crosbot_ogmbicp::GetRecentScans >::value();
  }
  static const char* value(const ::crosbot_ogmbicp::GetRecentScansResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CROSBOT_OGMBICP_MESSAGE_GETRECENTSCANS_H
