// Generated by gencpp from file crosbot/ColourMsg.msg
// DO NOT EDIT!


#ifndef CROSBOT_MESSAGE_COLOURMSG_H
#define CROSBOT_MESSAGE_COLOURMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crosbot
{
template <class ContainerAllocator>
struct ColourMsg_
{
  typedef ColourMsg_<ContainerAllocator> Type;

  ColourMsg_()
    : r(0)
    , g(0)
    , b(0)
    , a(0)  {
    }
  ColourMsg_(const ContainerAllocator& _alloc)
    : r(0)
    , g(0)
    , b(0)
    , a(0)  {
    }



   typedef uint8_t _r_type;
  _r_type r;

   typedef uint8_t _g_type;
  _g_type g;

   typedef uint8_t _b_type;
  _b_type b;

   typedef uint8_t _a_type;
  _a_type a;




  typedef boost::shared_ptr< ::crosbot::ColourMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crosbot::ColourMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ColourMsg_

typedef ::crosbot::ColourMsg_<std::allocator<void> > ColourMsg;

typedef boost::shared_ptr< ::crosbot::ColourMsg > ColourMsgPtr;
typedef boost::shared_ptr< ::crosbot::ColourMsg const> ColourMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crosbot::ColourMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crosbot::ColourMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crosbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'crosbot': ['/home/otan/3431/ass1/src/crosbot/crosbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crosbot::ColourMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crosbot::ColourMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot::ColourMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot::ColourMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot::ColourMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot::ColourMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crosbot::ColourMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a89b17adab5bedef0b554f03235d9b3";
  }

  static const char* value(const ::crosbot::ColourMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a89b17adab5bedeULL;
  static const uint64_t static_value2 = 0xf0b554f03235d9b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::crosbot::ColourMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crosbot/ColourMsg";
  }

  static const char* value(const ::crosbot::ColourMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crosbot::ColourMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 r\n\
uint8 g\n\
uint8 b\n\
uint8 a\n\
";
  }

  static const char* value(const ::crosbot::ColourMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crosbot::ColourMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ColourMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crosbot::ColourMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crosbot::ColourMsg_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
    s << indent << "a: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CROSBOT_MESSAGE_COLOURMSG_H
