// Generated by gencpp from file crosbot_explore/GetPath.msg
// DO NOT EDIT!


#ifndef CROSBOT_EXPLORE_MESSAGE_GETPATH_H
#define CROSBOT_EXPLORE_MESSAGE_GETPATH_H

#include <ros/service_traits.h>


#include <crosbot_explore/GetPathRequest.h>
#include <crosbot_explore/GetPathResponse.h>


namespace crosbot_explore
{

struct GetPath
{

typedef GetPathRequest Request;
typedef GetPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPath
} // namespace crosbot_explore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crosbot_explore::GetPath > {
  static const char* value()
  {
    return "41ca099eb8abb09e958f7da45a721668";
  }

  static const char* value(const ::crosbot_explore::GetPath&) { return value(); }
};

template<>
struct DataType< ::crosbot_explore::GetPath > {
  static const char* value()
  {
    return "crosbot_explore/GetPath";
  }

  static const char* value(const ::crosbot_explore::GetPath&) { return value(); }
};


// service_traits::MD5Sum< ::crosbot_explore::GetPathRequest> should match 
// service_traits::MD5Sum< ::crosbot_explore::GetPath > 
template<>
struct MD5Sum< ::crosbot_explore::GetPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_explore::GetPath >::value();
  }
  static const char* value(const ::crosbot_explore::GetPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_explore::GetPathRequest> should match 
// service_traits::DataType< ::crosbot_explore::GetPath > 
template<>
struct DataType< ::crosbot_explore::GetPathRequest>
{
  static const char* value()
  {
    return DataType< ::crosbot_explore::GetPath >::value();
  }
  static const char* value(const ::crosbot_explore::GetPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crosbot_explore::GetPathResponse> should match 
// service_traits::MD5Sum< ::crosbot_explore::GetPath > 
template<>
struct MD5Sum< ::crosbot_explore::GetPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_explore::GetPath >::value();
  }
  static const char* value(const ::crosbot_explore::GetPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_explore::GetPathResponse> should match 
// service_traits::DataType< ::crosbot_explore::GetPath > 
template<>
struct DataType< ::crosbot_explore::GetPathResponse>
{
  static const char* value()
  {
    return DataType< ::crosbot_explore::GetPath >::value();
  }
  static const char* value(const ::crosbot_explore::GetPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CROSBOT_EXPLORE_MESSAGE_GETPATH_H
