// Generated by gencpp from file crosbot_explore/GetPathRequest.msg
// DO NOT EDIT!


#ifndef CROSBOT_EXPLORE_MESSAGE_GETPATHREQUEST_H
#define CROSBOT_EXPLORE_MESSAGE_GETPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace crosbot_explore
{
template <class ContainerAllocator>
struct GetPathRequest_
{
  typedef GetPathRequest_<ContainerAllocator> Type;

  GetPathRequest_()
    : start()
    , end()  {
    }
  GetPathRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , end(_alloc)  {
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _end_type;
  _end_type end;




  typedef boost::shared_ptr< ::crosbot_explore::GetPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crosbot_explore::GetPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetPathRequest_

typedef ::crosbot_explore::GetPathRequest_<std::allocator<void> > GetPathRequest;

typedef boost::shared_ptr< ::crosbot_explore::GetPathRequest > GetPathRequestPtr;
typedef boost::shared_ptr< ::crosbot_explore::GetPathRequest const> GetPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crosbot_explore::GetPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crosbot_explore::GetPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crosbot_explore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_explore::GetPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_explore::GetPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_explore::GetPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_explore::GetPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_explore::GetPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_explore::GetPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crosbot_explore::GetPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "557eb839c2f06ff36431228da37da996";
  }

  static const char* value(const ::crosbot_explore::GetPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x557eb839c2f06ff3ULL;
  static const uint64_t static_value2 = 0x6431228da37da996ULL;
};

template<class ContainerAllocator>
struct DataType< ::crosbot_explore::GetPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crosbot_explore/GetPathRequest";
  }

  static const char* value(const ::crosbot_explore::GetPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crosbot_explore::GetPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose start\n\
geometry_msgs/Pose end\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::crosbot_explore::GetPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crosbot_explore::GetPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crosbot_explore::GetPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crosbot_explore::GetPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "end: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.end);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CROSBOT_EXPLORE_MESSAGE_GETPATHREQUEST_H
