// Generated by gencpp from file crosbot_explore/SetMode.msg
// DO NOT EDIT!


#ifndef CROSBOT_EXPLORE_MESSAGE_SETMODE_H
#define CROSBOT_EXPLORE_MESSAGE_SETMODE_H

#include <ros/service_traits.h>


#include <crosbot_explore/SetModeRequest.h>
#include <crosbot_explore/SetModeResponse.h>


namespace crosbot_explore
{

struct SetMode
{

typedef SetModeRequest Request;
typedef SetModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMode
} // namespace crosbot_explore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crosbot_explore::SetMode > {
  static const char* value()
  {
    return "ff63f6ea3c3e9b7504b2cb3ee0a09d92";
  }

  static const char* value(const ::crosbot_explore::SetMode&) { return value(); }
};

template<>
struct DataType< ::crosbot_explore::SetMode > {
  static const char* value()
  {
    return "crosbot_explore/SetMode";
  }

  static const char* value(const ::crosbot_explore::SetMode&) { return value(); }
};


// service_traits::MD5Sum< ::crosbot_explore::SetModeRequest> should match 
// service_traits::MD5Sum< ::crosbot_explore::SetMode > 
template<>
struct MD5Sum< ::crosbot_explore::SetModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_explore::SetMode >::value();
  }
  static const char* value(const ::crosbot_explore::SetModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_explore::SetModeRequest> should match 
// service_traits::DataType< ::crosbot_explore::SetMode > 
template<>
struct DataType< ::crosbot_explore::SetModeRequest>
{
  static const char* value()
  {
    return DataType< ::crosbot_explore::SetMode >::value();
  }
  static const char* value(const ::crosbot_explore::SetModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crosbot_explore::SetModeResponse> should match 
// service_traits::MD5Sum< ::crosbot_explore::SetMode > 
template<>
struct MD5Sum< ::crosbot_explore::SetModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_explore::SetMode >::value();
  }
  static const char* value(const ::crosbot_explore::SetModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_explore::SetModeResponse> should match 
// service_traits::DataType< ::crosbot_explore::SetMode > 
template<>
struct DataType< ::crosbot_explore::SetModeResponse>
{
  static const char* value()
  {
    return DataType< ::crosbot_explore::SetMode >::value();
  }
  static const char* value(const ::crosbot_explore::SetModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CROSBOT_EXPLORE_MESSAGE_SETMODE_H
