(cl:defpackage crosbot_explore-srv
  (:use )
  (:export
   "FOLLOWPATH"
   "<FOLLOWPATH-REQUEST>"
   "FOLLOWPATH-REQUEST"
   "<FOLLOWPATH-RESPONSE>"
   "FOLLOWPATH-RESPONSE"
   "GETPATH"
   "<GETPATH-REQUEST>"
   "GETPATH-REQUEST"
   "<GETPATH-RESPONSE>"
   "GETPATH-RESPONSE"
   "SETMODE"
   "<SETMODE-REQUEST>"
   "SETMODE-REQUEST"
   "<SETMODE-RESPONSE>"
   "SETMODE-RESPONSE"
  ))

